ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5433) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'ecommerce') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'ecommerce') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      schema: dw
      threads: 4
      keepalives_idle: 0
